/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        olive: {
          50: '#DFECC6',
          100: 'rgba(223, 236, 198, 0.33)',
          400: '#8E9C78',
          800: '#485C11',
        },
        neutral: {
          750: '#6F6F6F',
        },
        primary: '#091e03',
        'on-primary': '#ffffff',
        'primary-container': '#1e3314',
        'on-primary-container': '#839d74',
        secondary: '#50643c',
        'on-secondary': '#ffffff',
        'secondary-container': '#cde5b2',
        'on-secondary-container': '#53673e',
        tertiary: '#111c06',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#253118',
        'on-tertiary-container': '#8c9a79',
        surface: '#eeffde',
        'on-surface': '#0a2003',
        'surface-variant': '#ceebba',
        'on-surface-variant': '#44483f',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#dffdcb',
        'surface-container': '#d9f7c5',
        'surface-container-high': '#d4f1c0',
        'surface-container-highest': '#ceebba',
        'surface-bright': '#eeffde',
        'surface-dim': '#c6e3b2',
        outline: '#74796e',
        'outline-variant': '#c4c8bc',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#eeffde',
        'on-background': '#0a2003',
      },
      fontFamily: {
        crimson: ['"Crimson Text"', 'serif'],
        dm: ['"DM Sans"', 'sans-serif'],
        roboto: ['"Roboto"', 'sans-serif'],
        'roboto-mono': ['"Roboto Mono"', 'monospace'],
        playfair: ['"Playfair Display"', 'serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-xl': ['"Playfair Display"', 'serif'],
        'headline-lg': ['"Playfair Display"', 'serif'],
        'headline-md': ['"Playfair Display"', 'serif'],
        'display-hero': ['"Playfair Display"', 'serif'],
        'label-pill': ['"Playfair Display"', 'serif'],
        'label-numeric-lg': ['"Playfair Display"', 'serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-ui': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-kicker': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '54px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '42px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '30px', fontWeight: '500' }],
        'display-hero': ['72px', { lineHeight: '80px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-numeric-lg': ['40px', { lineHeight: '44px', fontWeight: '600' }],
        'label-pill': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-kicker': ['11px', { lineHeight: '16px', letterSpacing: '0.12em', fontWeight: '700' }],
        'label-ui': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
      spacing: {
        'gutter-mobile': '1rem',
        'gutter-desktop': '2rem',
        'space-xxs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'space-4xl': '6rem',
      },
      borderRadius: {
        '4xl': '30px',
        '5xl': '43px',
      }
    }
  },
  plugins: [],
};
