/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        olive: {
          50: '#DFECC6',
          100: 'rgba(223, 236, 198, 0.33)',
          400: '#8E9C78',
          800: '#485C11',
        },
        neutral: {
          750: '#6F6F6F',
        },
        primary: '#17210D',
        'on-primary': '#ffffff',
        'primary-container': '#485C11',
        'on-primary-container': '#FFFFFF',
        secondary: '#61733C',
        'on-secondary': '#ffffff',
        'secondary-container': '#DFECC6',
        'on-secondary-container': '#31400F',
        tertiary: '#31400F',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#EFD5C4',
        'on-tertiary-container': '#532C1B',
        surface: '#F7F8F2',
        'on-surface': '#17210D',
        'surface-variant': '#E7EDD8',
        'on-surface-variant': '#4F5744',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#F5F7EE',
        'surface-container': '#EEF2E4',
        'surface-container-high': '#E7EDD8',
        'surface-container-highest': '#DFECC6',
        'surface-bright': '#FAFBF7',
        'surface-dim': '#D8DEC9',
        outline: '#707766',
        'outline-variant': '#C8CEBC',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#F7F8F2',
        'on-background': '#17210D',
      },
      fontFamily: {
        crimson: ['"Crimson Text"', 'serif'],
        dm: ['"DM Sans"', 'sans-serif'],
        roboto: ['"Roboto"', 'sans-serif'],
        'roboto-mono': ['"Roboto Mono"', 'monospace'],
        playfair: ['"Crimson Text"', 'serif'],
        jakarta: ['"DM Sans"', 'sans-serif'],
        'headline-xl': ['"Crimson Text"', 'serif'],
        'headline-lg': ['"Crimson Text"', 'serif'],
        'headline-md': ['"Crimson Text"', 'serif'],
        'display-hero': ['"Crimson Text"', 'serif'],
        'label-pill': ['"Crimson Text"', 'serif'],
        'label-numeric-lg': ['"Crimson Text"', 'serif'],
        'body-lg': ['"DM Sans"', 'sans-serif'],
        'body-md': ['"DM Sans"', 'sans-serif'],
        'body-sm': ['"DM Sans"', 'sans-serif'],
        'label-ui': ['"DM Sans"', 'sans-serif'],
        'label-kicker': ['"DM Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '54px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '42px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '30px', fontWeight: '500' }],
        'display-hero': ['72px', { lineHeight: '80px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-numeric-lg': ['40px', { lineHeight: '44px', fontWeight: '600' }],
        'label-pill': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-kicker': ['11px', { lineHeight: '16px', letterSpacing: '0.12em', fontWeight: '700' }],
        'label-ui': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
      spacing: {
        'gutter-mobile': '1rem',
        'gutter-desktop': '2rem',
        'space-xxs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'space-4xl': '6rem',
      },
      borderRadius: {
        '4xl': '30px',
        '5xl': '43px',
      }
    }
  },
  plugins: [],
};
